apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Replace placeholder in AuthConfig with discovered Keycloak URL
patches:
  - target:
      kind: AuthConfig
      name: a2a-mcp-bridge-auth
    patch: |-
      - op: replace
        path: /spec/authentication/keycloak-jwt/jwt/issuerUrl
        value: https://keycloak-keycloak.apps.kagenti-ci.octo-emerging.redhataicoe.com/realms/master
