---
# Authorino Operator installation
# This is the controller that manages Authorino instances
apiVersion: v1
kind: Namespace
metadata:
  name: authorino-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: authorino-operator
  namespace: authorino-operator
spec:
  # No targetNamespaces = AllNamespaces mode (cluster-wide)
  # Authorino requires this to watch Authorino resources in any namespace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: authorino-operator
  namespace: authorino-operator
spec:
  channel: stable
  name: authorino-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
