apiVersion: v1
kind: Service
metadata:
  name: keycloak-keycloak-apps-kagenti-ci-octo-emerging-redhataicoe-com
  namespace: kagenti-a2a-mcp-bridge
spec:
  type: ExternalName
  externalName: keycloak-service.keycloak.svc.cluster.local
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
